# Generated by Django 3.0.3 on 2020-09-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='principal',
            new_name='age',
        ),
    ]
